[package]
name = "nucleon"
version = "0.0.1"
edition = "2021"
authors = ["Nicolas Le Manchet <nicolas@lemanchet.fr>"]

[dependencies]
log = "0.4.20"
argparse = "0.2.1"
mio = "0.5.0"
redis = "0.26.0"
env_logger = "0.11.5"
bytes = "0.3.0"
